### ISSUE TITLE
Make `launchAff_` operate only on `Aff Unit`

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript-contrib/purescript-aff#202]
**Problem**

I’m finding launchAff_ to be quite dangerous. When I have an interface that requires an Effect Unit but I need to perform some network calls I usually provide the callback with launchAff_ . Now I ran into a situation where I used launchAff_ on an Aff (Either Error Unit) which is not what I intended. Do you think it would hurt much if launchAff_ only worked on Aff Unit values? That way it would be similar to the warning about implicitly discarding values in a do block.

**Describe the solution you'd like**

`launchAff_` has the signature
```purescript
launchAff_ ∷ Aff Unit → Effect Unit
```

**Additional context**
I'm aware that this should cause a major version bump since it's a breaking change. I'm hopeful however, that *when* this change requires somebody to change their code it will improve its clarity or even catch potential bugs.

**Comment by garyb** [comment]
+1 from me! It's the same kind of thing `discard` is meant to prevent in a monadic context.

**Comment by JordanMartinez** [comment]
```purescript
main :: Effect Unit
main = launchAff_ $ void do
  problemNotSolved

**Comment by i-am-the-slime** [comment]
@JordanMartinez I don't understand, can you elaborate?

**Comment by garyb** [comment]
I don't really think that's an issue, using `unsafeCoerce` there would have the same effect :wink:, it's the same situation as `discard` too, `void` is supposed to let you do that.

**Comment by JordanMartinez** [comment]
Ah, I misread the opening issue. The issue is that `launchAff_` will convert things to `Aff Unit` when you may not want it to. By changing the type signature, it brings this issue immediately to the developer. The developer will either think "Oh no! I don't want `launchAff_` to discard that value! Let me fix that" (as is the case that opened this issue) or "Ah... I don't care about that value. Nothing a `void` can't fix." So, it's a minor annoyance (and breaking change) for most developers but otherwise makes the resulting code much safer.

Please disregard my former comment.

**Comment by wclr** [comment]
`launchAff_` is just a shortcut for using `void`, to me, it's not justified why such things exist at all. Trying to make things ~~simplier~~ easier we get less predictable code and behaviour. So I would consider deprecating and removing such things.

**Comment by cryogenian** [comment]
👍 for removing `launchAff_`
